name: NunDB Python CI/CD

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio websockets pytest-timeout

      - name: Run NunDB Docker container
        run: |
          docker run -d --env NUN_USER=user-name \
                        --env NUN_PWD=user-pwd \
                        --env NUN_DBS_DIR="/data" \
                        --mount type=bind,source="/tmp",target=/data \
                        -p 3013:3013 -p 3012:3012 -p 3014:3014 \
                        --name nun-test mateusfreira/nun-db
          sleep 5 

      - name: Run tests with pytest
        run: |
          pytest test_nundb.py

      - name: Stop Docker container
        if: always()
        run: docker stop nun-test
